header:
  paths:
    - "**/*.c"
    - "**/*.h"
  license:
    pattern: |
      .*\.(c|h)
      .*

      Portions Copyright © 2018-2025, Percona LLC and/or its affiliates

      Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group

      Portions Copyright (c) 1994, The Regents of the University of California

      IDENTIFICATION
         contrib/pg_stat_monitor/.*\.(c|h)

  comment: never
